# Cole colorscheme for Tmux
# A stationery-inspired theme with vintage earth tones

# Color palette
set -g @cole_background "#1A1D23"
set -g @cole_background_accent "#3d3d3d"
set -g @cole_foreground "#f2e6cf"
set -g @cole_accent "#b38d59"
set -g @cole_accent_bright "#cc9b52"
set -g @cole_green "#2e9969"
set -g @cole_green_bright "#66cc69"
set -g @cole_red "#cc5d4b"
set -g @cole_black "#121212"
set -g @cole_border "#3d3d3d"

# Set vi style key bindings in copy mode
set -g mode-keys vi

# Status bar
set -gF status-style "bg=default,fg=#{@cole_foreground}"
set -g status-position top
set -g status-justify centre
set -g status-left "#[bg=#{@cole_red},fg=#{@cole_black},bold] #S #[bg=default,fg=#{@cole_foreground}]"
set -g status-right-length 100
set -g status-right " #[fg=colour235,bg=#{@cole_accent},bold] %a %d-%m-%Y #[fg=colour235,bg=#{@cole_accent},bold] %I:%M %p "

# Window list styles
setw -gF window-status-style "bg=#{@cole_background_accent},fg=#{@cole_foreground}"
setw -gF window-status-current-style "bg=#{@cole_accent},fg=#{@cole_black},bold"
setw -g window-status-separator ""

# Format window names in list
setw -g window-status-format " #I #W "
setw -g window-status-current-format " #I #W "

# Panes styling
set -g pane-border-lines spaces
# set -g pane-border-status top
# set -g pane-border-format " #P #W "
# set -g pane-border-format ""
# set -gF pane-border-style "fg=#{@cole_border}"
# set -gF pane-active-border-style "fg=#{@cole_accent_bright}"

# Messages
set -gF message-style "bg=#{@cole_black},fg=#{@cole_foreground}"
set -gF message-command-style "bg=#{@cole_black},fg=#{@cole_foreground}"
set -gF prompt-cursor-colour "#{@cole_foreground}"

# Copy mode
setw -gF copy-mode-match-style "bg=#{@cole_green},fg=#{@cole_black}"
setw -gF copy-mode-current-match-style "bg=#{@cole_green_bright},fg=#{@cole_black}"
